name: Build and Test PR

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'
        
    - name: Install uv
      run: |
        curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/astral-sh/uv/main/install.sh | sh
        export PATH="$HOME/.cargo/bin:$PATH"
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH
        uv --version
        
    - name: Install dependencies
      run: |
        uv pip install -e ".[dev]"
        
    - name: Run linters
      run: |
        uv run ruff check .
        uv run ruff format --check .
        
    - name: Type check
      run: |
        uv run mypy s3_navigator
        
    - name: Test with pytest
      run: |
        uv run pytest --cov=s3_navigator --cov-report=term
        
    - name: Build package
      run: |
        uv pip install build
        uv run python -m build
        
    - name: Verify package
      run: |
        uv pip install twine
        uv run twine check dist/*