name: Build and Test PR

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'
        
    - name: Install uv
      run: |
        # Install using pip instead of the installer script
        python -m pip install --upgrade pip
        python -m pip install uv
        uv --version
        
    - name: Install dependencies
      run: |
        uv pip install --system -e ".[dev]"
               
    - name: Test with pytest
      run: |
        python -m pytest --cov=s3_navigator --cov-report=term
        
    - name: Build package
      run: |
        uv pip install --system build
        python -m build
        
    - name: Verify package
      run: |
        uv pip install --system twine
        python -m twine check dist/*