name: Code Coverage Comment

on:
  workflow_run:
    workflows: ["Tests"]
    types:
      - completed

jobs:
  coverage:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.event == 'pull_request'
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download coverage reports
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: Tests
          workflow_conclusion: success
          name: coverage-report-ubuntu-latest-py3.9
          run_id: ${{ github.event.workflow_run.id }}
          path: coverage-reports

      - name: Get PR number
        id: pr-number
        uses: potiuk/get-workflow-origin@v1_5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          sourceRunId: ${{ github.event.workflow_run.id }}

      - name: Create comment with coverage
        if: steps.pr-number.outputs.pullRequestNumber != ''
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          number: ${{ steps.pr-number.outputs.pullRequestNumber }}
          path: coverage-reports/coverage.xml
          recreate: true
          message: |
            ## Code Coverage Report
            
            ```
            $(coverage report)
            ```
            
            <details>
              <summary>Coverage XML Report</summary>
              
              ```xml
              $(cat coverage-reports/coverage.xml)
              ```
            </details>