name: Coverage Badge

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  coverage-badge:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'
          
      - name: Install uv
        run: |
          python -m pip install --upgrade pip
          python -m pip install uv
          
      - name: Install dependencies
        run: |
          uv pip install --system -e ".[dev]"
          
      - name: Generate coverage
        run: |
          python -m pytest --cov=s3_navigator --cov-report=xml
          
      - name: Create coverage badge
        run: |
          COVERAGE=$(python -c "import xml.etree.ElementTree as ET; print(round(float(ET.parse('coverage.xml').getroot().attrib['line-rate']) * 100))")
          
          # Create a temporary SVG file with coverage percentage
          cat > coverage-badge.svg << EOF
          <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="96" height="20" role="img" aria-label="coverage: ${COVERAGE}%">
              <title>coverage: ${COVERAGE}%</title>
              <linearGradient id="s" x2="0" y2="100%">
                  <stop offset="0" stop-color="#bbb" stop-opacity=".1"/>
                  <stop offset="1" stop-opacity=".1"/>
              </linearGradient>
              <clipPath id="r">
                  <rect width="96" height="20" rx="3" fill="#fff"/>
              </clipPath>
              <g clip-path="url(#r)">
                  <rect width="61" height="20" fill="#555"/>
                  <rect x="61" width="35" height="20" fill="${COVERAGE >= 80 ? '#4c1' : COVERAGE >= 70 ? '#97CA00' : COVERAGE >= 60 ? '#dfb317' : '#e05d44'}"/>
                  <rect width="96" height="20" fill="url(#s)"/>
              </g>
              <g fill="#fff" text-anchor="middle" font-family="Verdana,Geneva,DejaVu Sans,sans-serif" text-rendering="geometricPrecision" font-size="110">
                  <text aria-hidden="true" x="315" y="150" fill="#010101" fill-opacity=".3" transform="scale(.1)" textLength="510">coverage</text>
                  <text x="315" y="140" transform="scale(.1)" fill="#fff" textLength="510">coverage</text>
                  <text aria-hidden="true" x="775" y="150" fill="#010101" fill-opacity=".3" transform="scale(.1)" textLength="250">${COVERAGE}%</text>
                  <text x="775" y="140" transform="scale(.1)" fill="#fff" textLength="250">${COVERAGE}%</text>
              </g>
          </svg>
          EOF
          
          mkdir -p coverage
          cp coverage-badge.svg coverage/badge.svg
          
      - name: Upload badge as artifact
        uses: actions/upload-artifact@v3
        with:
          name: coverage-badge
          path: coverage/badge.svg
          
      - name: Deploy badge to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: coverage
          branch: gh-pages
          target-folder: badges