name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9, 3.10, 3.11]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install uv
      run: |
        curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/astral-sh/uv/main/install.sh | sh
        export PATH="$HOME/.cargo/bin:$PATH"
        uv --version
    - name: Install dependencies
      run: |
        uv pip install -e ".[dev]"
    - name: Lint
      run: |
        uv run black --check .
        uv run flake8 .
    - name: Type check
      run: |
        uv run mypy s3_navigator
    - name: Test
      run: |
        uv run pytest
